//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap")]
    public interface Calcula_AreaWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Dato1 del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cuadrado", ReplyAction="*")]
        ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoResponse Cuadrado(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoResponse> CuadradoAsync(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Base del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rectagulo", ReplyAction="*")]
        ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloResponse Rectagulo(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Rectagulo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloResponse> RectaguloAsync(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Radio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Circulo", ReplyAction="*")]
        ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoResponse Circulo(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Circulo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoResponse> CirculoAsync(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuadradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cuadrado", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequestBody Body;
        
        public CuadradoRequest() {
        }
        
        public CuadradoRequest(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuadradoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Dato1;
        
        public CuadradoRequestBody() {
        }
        
        public CuadradoRequestBody(string Dato1) {
            this.Dato1 = Dato1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuadradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuadradoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoResponseBody Body;
        
        public CuadradoResponse() {
        }
        
        public CuadradoResponse(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuadradoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CuadradoResult;
        
        public CuadradoResponseBody() {
        }
        
        public CuadradoResponseBody(string CuadradoResult) {
            this.CuadradoResult = CuadradoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RectaguloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Rectagulo", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequestBody Body;
        
        public RectaguloRequest() {
        }
        
        public RectaguloRequest(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RectaguloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Base;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Altura;
        
        public RectaguloRequestBody() {
        }
        
        public RectaguloRequestBody(string Base, string Altura) {
            this.Base = Base;
            this.Altura = Altura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RectaguloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RectaguloResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloResponseBody Body;
        
        public RectaguloResponse() {
        }
        
        public RectaguloResponse(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RectaguloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RectaguloResult;
        
        public RectaguloResponseBody() {
        }
        
        public RectaguloResponseBody(string RectaguloResult) {
            this.RectaguloResult = RectaguloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CirculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Circulo", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequestBody Body;
        
        public CirculoRequest() {
        }
        
        public CirculoRequest(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CirculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Radio;
        
        public CirculoRequestBody() {
        }
        
        public CirculoRequestBody(string Radio) {
            this.Radio = Radio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CirculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CirculoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoResponseBody Body;
        
        public CirculoResponse() {
        }
        
        public CirculoResponse(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CirculoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CirculoResult;
        
        public CirculoResponseBody() {
        }
        
        public CirculoResponseBody(string CirculoResult) {
            this.CirculoResult = CirculoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Calcula_AreaWebServiceSoapChannel : ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Calcula_AreaWebServiceSoapClient : System.ServiceModel.ClientBase<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap>, ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap {
        
        public Calcula_AreaWebServiceSoapClient() {
        }
        
        public Calcula_AreaWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Calcula_AreaWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Calcula_AreaWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Calcula_AreaWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoResponse ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap.Cuadrado(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequest request) {
            return base.Channel.Cuadrado(request);
        }
        
        public string Cuadrado(string Dato1) {
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequest inValue = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequest();
            inValue.Body = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequestBody();
            inValue.Body.Dato1 = Dato1;
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoResponse retVal = ((ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap)(this)).Cuadrado(inValue);
            return retVal.Body.CuadradoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoResponse> ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap.CuadradoAsync(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequest request) {
            return base.Channel.CuadradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoResponse> CuadradoAsync(string Dato1) {
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequest inValue = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequest();
            inValue.Body = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CuadradoRequestBody();
            inValue.Body.Dato1 = Dato1;
            return ((ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap)(this)).CuadradoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloResponse ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap.Rectagulo(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequest request) {
            return base.Channel.Rectagulo(request);
        }
        
        public string Rectagulo(string Base, string Altura) {
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequest inValue = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequest();
            inValue.Body = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequestBody();
            inValue.Body.Base = Base;
            inValue.Body.Altura = Altura;
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloResponse retVal = ((ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap)(this)).Rectagulo(inValue);
            return retVal.Body.RectaguloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloResponse> ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap.RectaguloAsync(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequest request) {
            return base.Channel.RectaguloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloResponse> RectaguloAsync(string Base, string Altura) {
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequest inValue = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequest();
            inValue.Body = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.RectaguloRequestBody();
            inValue.Body.Base = Base;
            inValue.Body.Altura = Altura;
            return ((ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap)(this)).RectaguloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoResponse ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap.Circulo(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequest request) {
            return base.Channel.Circulo(request);
        }
        
        public string Circulo(string Radio) {
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequest inValue = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequest();
            inValue.Body = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequestBody();
            inValue.Body.Radio = Radio;
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoResponse retVal = ((ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap)(this)).Circulo(inValue);
            return retVal.Body.CirculoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoResponse> ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap.CirculoAsync(ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequest request) {
            return base.Channel.CirculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoResponse> CirculoAsync(string Radio) {
            ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequest inValue = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequest();
            inValue.Body = new ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.CirculoRequestBody();
            inValue.Body.Radio = Radio;
            return ((ServiciosWE.Practica.Net.client.AreRectagulo_ServiceReference.Calcula_AreaWebServiceSoap)(this)).CirculoAsync(inValue);
        }
    }
}
